# Generated by Django 3.0.5 on 2020-04-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_publications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publications',
            new_name='Publication',
        ),
    ]
